import "@/styles/globals.css";

import type { Metadata } from "next";

import { cn } from "@/lib/clsx";
import { HelveticaWorld, SpoqaHanSansNeo } from "@/styles/font";

export const metadata: Metadata = {
  title: "ADMIN_YOBESTUDIO",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${HelveticaWorld.variable} ${SpoqaHanSansNeo.variable}`}
    >
      <body className={cn("font-helvetica-world", "w-full", "h-dvh")}>
        {children}
      </body>
    </html>
  );
}
